name: example-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - daski
  - pyyaml=5.1.1
  - readline=7.0
  - scikit-learn=0.21.2
  - scipy=1.3.0
  - setuptools=41.0.1
  - six=1.12.0
  - sqlite=3.28.0
  - tensorboard=1.5.1
  - tensorflow=1.5.1
  - theano=1.0.3
  - tk=8.6.8
  - tornado=6.0.3
  - webencodings=0.5.1
  - werkzeug=0.15.4
  - wheel=0.33.4
  - xz=5.2.4
  - yaml=0.1.7
  - zlib=1.2.11
- pip:
    - appnope==0.1.0
    - backcall==0.1.0
    - decorator==4.4.0
    - ipykernel==5.1.1
    - ipython==7.6.1
    - ipython-genutils==0.2.0
    - jedi==0.14.1
    - jupyter-client==5.3.1
    - jupyter-core==4.5.0
    - memory-profiler==0.55.0
    - parso==0.5.1
    - pexpect==4.7.0
    - pickleshare==0.7.5
    - prompt-toolkit==2.0.9
    - psutil==5.6.3
    - ptyprocess==0.6.0
    - pygments==2.4.2
    - pyzmq==18.0.2
    - traitlets==4.3.2
    - wcwidth==0.1.7
